### ISSUE TITLE
z-index tokens

### ISSUE THREAD

**Issue by nathanyoung** [palmetto/palmetto-design-tokens#42]
create global set of z-index tokens to be used for things like

- modals
- overlays
- popover menus (e.g. calendars, button dropdown menu)

Currently used by logistics app: https://github.com/palmetto/logistics-platform/blob/master/packages/app/src/styles/functions.scss

**Comment by nathanyoung** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [z-index](https://trello.com/c/VvJ89Wai/146-z-index)

**Comment by juanfabrega** [comment]
@nathanyoung I think it is safe to say that since logistics-app uses bootstrap they are also defaulting to these under the hood. Not saying we need to follow-suit, just something to keep in mind.

Bootstrap uses two z-index scales. One for elements within a component, which is 0 - 3, and another for "overlays" which is detailed here: https://getbootstrap.com/docs/4.0/layout/overview/#z-index
